
spring.application.name: function-calling
spring:
  docker:
    compose:
      enabled: true
      file: src/main/docker/docker-compose.yml
      lifecycle-management: start_only
      readiness:
        wait: never
      skip:
        in-tests: false
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      jdbc-url: jdbc:postgresql://localhost:5440/postgres
  liquibase:
    enabled: false
  cloud:
    zookeeper:
      discovery:
        enabled: false
      enabled: false

code-runner:
  registrations:
    - id: "echo"
      command: "echo"
      description: "Simple echo command"
      arguments: "Hello, World!"
      timeoutSeconds: 30
      enabled: true
    - id: "ls"
      command: "ls"
      description: "List directory contents"
      arguments: "-la"
      timeoutSeconds: 30
      enabled: true
    - id: "pwd"
      command: "pwd"
      description: "Print working directory"
      timeoutSeconds: 15
      enabled: true
    - id: "cdc-agents-test"
      command: "uv"
      working-directory: "/Users/hayde/IdeaProjects/drools/python_parent/packages/cdc_agents"
      arguments: "run cdc-agents-test"
      description: "Test CDC agents"
      enabled: true
    - id: "run-test-graph-all"
      command: "/bin/zsh"
      arguments: "all-tests-test-graph.sh"
      working-directory: "/Users/hayde/IdeaProjects/drools"
      description: "Run pipeline for all"
      reporting-paths:
        - file:///Users/hayde/IdeaProjects/drools/commit-diff-context-graphql/build/reports/tests/test/index.html
        - file:///Users/hayde/IdeaProjects/drools/test_graph/build/test-report-log.log
        - file:///Users/hayde/IdeaProjects/drools/test_graph/build/reports/tests/test/index.html


logging.config: classpath:logback.xml
logging:
  level:
    org.springframework.boot: INFO

endpoints:
  zookeeper:
    enabled: false