services:
  commit-diff-postgres:
    image: localhost:5001/postgres-pgvector
    container_name: function-calling-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - function-calling:/var/lib/postgresql/embedding
    ports:
      - "5440:5432"
volumes:
  function-calling:
